### PR TITLE
Notify coordinator admin for new disputes

### PR DESCRIPTION
**Pull request by KoalaSat**
## What does this PR do?

This PR introduces an extra notification when a new disputed is created which (if configured) will notify to the admin of the coordinator by using the Notifications bot.

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Hey @KoalaSat, suuper useful fix. Please post an invoice for 50K.

**Comment by Reckless-Satoshi** [comment]
Coordinator image #9ef84b2 has this new feature. https://hub.docker.com/layers/recksato/robosats/9ef84b2/images/sha256-eeb2c99f5a4dc9f4a16f6cf553a0307651e1543b975690681a05e92206f3cc8f?context=explore

**Comment by KoalaSat** [comment]
```
lnbc500u1pnq2tdcpp5gcn6pyv2q2qlnx484had592ah3cnm78gvmwaw3pj4jhgnr6ekcwqdqqcqzzsxqymwaqsp57t5aeg7wsmmcr8xeqrkzw6c2nwgy4vxgy8xq9enmp4969uv0wzaq9qyyssqlj7mdxhnvqk2qd50g3n2twcdj05vu7lkhln5l8uetu8qvezesul38lkj3mj5hgww30ad0ylu0v5prj5kfrgqq8v47smmlk79m3zv5ssqx5c2mg
```

**Comment by Reckless-Satoshi** [comment]
> lnbc500u1pnq2tdcpp5gcn6pyv2q2qlnx484had592ah3cnm78gvmwaw3pj4jhgnr6ekcwqdqqcqzzsxqymwaqsp57t5aeg7wsmmcr8xeqrkzw6c2nwgy4vxgy8xq9enmp4969uv0wzaq9qyyssqlj7mdxhnvqk2qd50g3n2twcdj05vu7lkhln5l8uetu8qvezesul38lkj3mj5hgww30ad0ylu0v5prj5kfrgqq8v47smmlk79m3zv5ssqx5c2mg

428134924f6a31a4d7fd7a7c2b94d407616b30d493eb2c885ff3c4513ca03b40

**Pull request merged**
