### PR TITLE
switch to the core cln Decode Request

### PR DESCRIPTION
**Pull request by jerryfletcher21**
## What does this PR do?
Since DecodeBolt11 was [removed](https://github.com/daywalker90/holdinvoice/commit/d51fd0339030c4a4f97dc92ab148b37340ae6370) from holdinvoice, switch to the core cln Decode Request.
Before merging also docker cln should be updated.

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Thank you @jerryfletcher21 :rocket: 

What sort of update does the docker image need? Does it suffice with updating the line `FROM elementsproject/lightningd:v23.08 as final` to `FROM elementsproject/lightningd:24.05 as final` ?

**Comment by daywalker90** [comment]
Merged with #1336, thanks @jerryfletcher21 for doing this :)

**Comment by Reckless-Satoshi** [comment]
Thank you @jerryfletcher21 , this PR changes are now in `main` 🚀 

Please accept a 70K Sats tip from the DevFund (invoice with +1 week expiration if possible).

**Comment by jerryfletcher21** [comment]
> Merged with #1336, thanks @jerryfletcher21 for doing this :)

Thanks to you for doing the update!

**Comment by jerryfletcher21** [comment]
> Thank you @jerryfletcher21 , this PR changes are now in `main` 🚀
> 
> Please accept a 70K Sats tip from the DevFund (invoice with +1 week expiration if possible).

lnbc700u1pn8y893sp55tsmgerd696yalsclhdre2sdu0fzd7rcsmgtr77y6v65ms76gt8spp5znsr86j4qkth4rdft6s4pn0mz6f68h3ttl8l34xu0e485pywhvwsdqqxq9zf6sqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgqgr3rls3q0h8kpq8wwk2j0uh2tg95w5qgvxgmq260ja9tudjzavd89sh5ksraefk3y2pk782dsdfnjlt2n6r5v0pdt022q2wygmzhhlcqhjc5lx

**Comment by Reckless-Satoshi** [comment]
> lnbc700u1pn8y893sp55tsmgerd696yalsclhdre2sdu0fzd7rcsmgtr77y6v65ms76gt8spp5znsr86j4qkth4rdft6s4pn0mz6f68h3ttl8l34xu0e485pywhvwsdqqxq9zf6sqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgqgr3rls3q0h8kpq8wwk2j0uh2tg95w5qgvxgmq260ja9tudjzavd89sh5ksraefk3y2pk782dsdfnjlt2n6r5v0pdt022q2wygmzhhlcqhjc5lx


8f7fb5a585b8e435c9a1e4aff5f88878a22704aa101e9d715848ed87a81f232b

**Pull request closed without merging**
