### PR TITLE
small fix in get_exchange_rates

### PR DESCRIPTION
**Pull request by jerryfletcher21**
## What does this PR do?
While running tests, the `print(e)` was printing an annoying list of currencies. 
Removing it it is also more coherent with the other currencies providers below.

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Nice, thank you for this fix!

Merging! :rocket: Please post an invoice for 15K with a veeery long expiration time (I keep missing them).

**Comment by jerryfletcher21** [comment]
> Please post an invoice for 15K with a veeery long expiration time (I keep missing them).

lnbc150u1png4n8tsp5u7r5yt4e2z9per38cj0l3duzlkj3980cmruss392pupmvfl3glzqpp5cterzp9wjecndkxt4rgqxmcl9cu0yreuxxhe4sg7s8ntqh6mu7nsdqqxq9zf6sqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgq0dr8njzv6vxet3zfmts0t6f4f774p4v0dynmknj5xclekjeqkv5x7lvw3z48ggdzvss5pvllxuvlet48qvya7lpn9hnc7ytl98crdsgpatju0s

**Comment by jerryfletcher21** [comment]
@KoalaSat 

`lnbc150u1p58pujdsp5jf2gf4y8w2c35k6xtxwjv0h95wy9w3sqc9gvmgj0599d5z82dntspp5wlka5l4c48n7avjacskgdn82cxgm3mx43mruhda6xx0kt05r6qssdqqxq9yn4qqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgqkm3gw6w9hc0tly8uaea9s4e6drs242uxunpht3w93ss3jcnmu9vjnwnkg34dy6ltct90nynqyeztztengkvp0hlnh7nl70am80ntclsqcttkzp`

**Comment by KoalaSat** [comment]
62882c2adf2c2d0294b0495a6475eaec4e45745cef42c0ebd7bb4668b48eeb6c

**Pull request merged**
