### PR TITLE
Adds Italian translations

### PR DESCRIPTION
**Pull request by LeoSpyke**
## What does this PR do?
Translates the Italian sections and fixes the full path to `locales` in the `02-languages.md`.

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Woop, woop! :rocket:  Thank you for going over the Italian locale and gap-filling all of the new phrases that were missing. 

Should we merge as is, or do you plan to add more commits to this PR?

**Comment by LeoSpyke** [comment]
Thank you for the feedback @Reckless-Satoshi!
Yes, I'm planning to finish the job the in next few days, meanwhile if you prefer I can mark the PR as Draft until completed.

**Comment by LeoSpyke** [comment]
I think the PR is ready.
Thank you.

**Comment by Reckless-Satoshi** [comment]
> Thank you.

No, thank you!! Translations are very out of date now, so it's great to go over them. Please, post an invoice for 10K Sats for a small tip :)

**Comment by LeoSpyke** [comment]
lnbc100u1pjg72jxpp523xlldmdpzz3r3dpvdc8zrgydqxxy3ykx2n9p36jmqh470e9l8zqdqu2askcmr9wssx7e3q2dshgmmndp5scqzzsxqyz5vqsp5j4ky85s55unc6f3qlzs40hzd7mp3kc7k3lvx9zdn4kfwtanfw9fq9qyyssq3gr6xuvmej6cm5232jdtzp94fwrj5c8h6jjmumz7z7qvdfec0x3qjfmxj5dcftqvx2zx4mjxz243n5fqxcsrugaj72vz0ayturplfscqttwkea

Thank you again! :)

**Comment by Reckless-Satoshi** [comment]
> lnbc100u1pjg72jxpp523xlldmdpzz3r3dpvdc8zrgydqxxy3ykx2n9p36jmqh470e9l8zqdqu2askcmr9wssx7e3q2dshgmmndp5scqzzsxqyz5vqsp5j4ky85s55unc6f3qlzs40hzd7mp3kc7k3lvx9zdn4kfwtanfw9fq9qyyssq3gr6xuvmej6cm5232jdtzp94fwrj5c8h6jjmumz7z7qvdfec0x3qjfmxj5dcftqvx2zx4mjxz243n5fqxcsrugaj72vz0ayturplfscqttwkea

217511ef0b89124eef7f45fdb14f5afa7e07fe7490eebae6125ca28ccd047a91

**Pull request merged**
