### PR TITLE
Prepare release for F-Droid

### PR DESCRIPTION
**Pull request by KoalaSat**
## What does this PR do?
These are changes requested by https://github.com/RoboSats/robosats/issues/1261#issuecomment-2455152829 in order to prepare the app for the F-Droid repo:

- Updated existing `librobonames` and `librobohash` to its latest commit on https://github.com/RoboSats/robo-identities/commit/c95a9f563bf50377f82665661152ee42097e773c
- Removed x86 build due to the lack of robo libraries for it

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by KoalaSat** [comment]
Build tested and working :+1:

**Comment by licaon-kter** [comment]
umm no x86_64 librobo*.so's?

**Comment by KoalaSat** [comment]
> umm no x86_64 librobo*.so's?

The x86_64 are exactly the same https://github.com/RoboSats/robosats/tree/main/mobile/android/app/src/main/jniLibs/x86_64 , no changes

**Comment by licaon-kter** [comment]
next
```
$ strings mobile/android/app/src/main/jniLibs/arm64-v8a/librobonames.so | grep rustc\ version
rustc version 1.81.0-nightly (20ae37c18 2024-07-07)
```
I'll try to match the same version

**Comment by licaon-kter** [comment]
no joy, even matching your version with `rustup-init.sh -y --default-toolchain nightly-2024-07-08` that gets me `rustc version 1.81.0-nightly (20ae37c18 2024-07-07)` the .so's are so very different

**Comment by licaon-kter** [comment]
@linsui any ideas to fix this diff? 
[librn.log.7z.zip](https://github.com/user-attachments/files/17666703/librn.log.7z.zip)

**Comment by licaon-kter** [comment]
ah, I thought I looked at that, nice catch, brb

**Comment by licaon-kter** [comment]
I got some paths cleaned up with 
```
    - export CARGO_ENCODED_RUSTFLAGS='--remap-path-prefix=/home/vagrant=/root --remap-path-prefix=/home/vagrant/build/srclib/robo-identities=/root'
    - cargo --config "trim-paths = true" ndk -t armeabi-v7a -t arm64-v8a -t x86_64
        -o ./target build --release
```

but the .so is filled with `/home/vagrant/.cargo/registry/src/index.crates.io-6f17d22bba15001f/somelib-version...` references, yes this whole string is everywhere

any idea how to clean this up too? 

I've searched for other ways to clean but didn't find the right command yet to remove the crates information from the .so file

eg https://github.com/rust-lang/cargo/issues/13171 and many more

**Comment by licaon-kter** [comment]
Looks like managing `CARGO_HOME` to match upstream (`/root/.cargo`?) moves me closer, no more odd paths

rebuilding in full, brb

**Comment by licaon-kter** [comment]
yeah, CARGO_HOME did it :tada: 

all those trim and remap tricks were useless :shrug: 

@KoalaSat do merge this and maybe tag a new release so we can test reproducibility in full

**Comment by KoalaSat** [comment]
> yeah, CARGO_HOME did it 🎉
> 
> all those trim and remap tricks were useless 🤷
> 
> @KoalaSat do merge this and maybe tag a new release so we can test reproducibility in full

Congrats!!! Alright, we are planning a next release probably for next week. I'll keep you updated here 🚀

**Comment by KoalaSat** [comment]
@licaon-kter new release just launched!

**Pull request merged**
