### PR TITLE
fix: Remove .js files from linting

### LINKED ISSUE #591: Remove linting errors on frontend
**Describe the bug**
There are a great number of linting errors in the frontend code

I would be willing to clean these up using sane adjustments to the eslint config and any other necessary refactors.

### PR DESCRIPTION
**Pull request by nullcount**
## What does this PR do?
Follow-up PR from the conversation in PR #1048
This PR removes .js files from eslint checking.

EDIT: someone should close #591 since it's a rewarded task and seems to already be complete in this branch

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Hey @nullcount  thank you for this contribution!

#591 closed. 

Sorry about the un-closed rewarded task issue situation. It is unfortunate and it is totally my fault to have not double checked that the issue closed when the PR was merged.

I would not like to break the implicit deal that stands when a rewarded task is completed, but I think 400K Sats for this PR would put to shame the latests contributions by KoalaSat where he found and fixed several important app-breaking bugs for a tip of 150K Sats. In this case it would have been very helpful to, following the rewarded tasks guideline, first drop a message in the issue thread for task assignation. I hope you accept a 100K tip for this contribution, please post an invoice from a proxy wallet with a long expiration time (+24h). Thank you and apologies once again.

**Comment by nullcount** [comment]
@Reckless-Satoshi Thanks for the offer to tip anyways. Going forward, I will ask to be assigned to a ticket before submitting work.

lnbc999993900p1pjendzvpp55legh9knx57fe4npalsc6talalrsy5u42k9s32gaw8y56qsrnv2qdqqcqzd7xqyznaasp5s6e85lfpxnz0jkweuyq3l79w8ydd0hvn87cqxg547pfdt7pw7nts9qyyssqwjlxjezzal53jl8f9htep6svhtvrezyzpel4lg9kf80kf9szqk8r8cj4chdhtmltd962qallsvgl6q454wk97elpfne3y74y7nu2gpgp8l3gwr

**Comment by Reckless-Satoshi** [comment]
> lnbc999993900p1pjendzvpp55legh9knx57fe4npalsc6talalrsy5u42k9s32gaw8y56qsrnv2qdqqcqzd7xqyznaasp5s6e85lfpxnz0jkweuyq3l79w8ydd0hvn87cqxg547pfdt7pw7nts9qyyssqwjlxjezzal53jl8f9htep6svhtvrezyzpel4lg9kf80kf9szqk8r8cj4chdhtmltd962qallsvgl6q454wk97elpfne3y74y7nu2gpgp8l3gwr

Having issues to make the payment arrive: "This node does not accept keysend payments". I guess some sort of proxying is taking place? The payment is certainly not a keysend payment.

**Comment by Reckless-Satoshi** [comment]
> lnbc999993900p1pjendzvpp55legh9knx57fe4npalsc6talalrsy5u42k9s32gaw8y56qsrnv2qdqqcqzd7xqyznaasp5s6e85lfpxnz0jkweuyq3l79w8ydd0hvn87cqxg547pfdt7pw7nts9qyyssqwjlxjezzal53jl8f9htep6svhtvrezyzpel4lg9kf80kf9szqk8r8cj4chdhtmltd962qallsvgl6q454wk97elpfne3y74y7nu2gpgp8l3gwr

Hey @nullcount retried again today, it seems the invoice has now expired. Could you post a new one?

**Comment by nullcount** [comment]
@Reckless-Satoshi please try this invoice:

lnbc999543450p1pjeac34pp59azh8nu8mzzm3cawf2nn9axjzq2yltkx4ykyqlhzwpvdd7cczhrqdqqcqzd7xqyd9j8sp572vfhl0zcs7dds42p4cu6ynvw2c2xskjmqjt3e8utg3f7pngyvxq9qyyssqck0dql6as22elmd8f4h3rzt23jk9fgfnduj0x9lecuzxtds0f67shu7mxc4pxyeuusz6tjk565sceazflxa5rjhfkncd6vyzplvwyuqqlcam23

**Comment by Reckless-Satoshi** [comment]
> lnbc999543450p1pjeac34pp59azh8nu8mzzm3cawf2nn9axjzq2yltkx4ykyqlhzwpvdd7cczhrqdqqcqzd7xqyd9j8sp572vfhl0zcs7dds42p4cu6ynvw2c2xskjmqjt3e8utg3f7pngyvxq9qyyssqck0dql6as22elmd8f4h3rzt23jk9fgfnduj0x9lecuzxtds0f67shu7mxc4pxyeuusz6tjk565sceazflxa5rjhfkncd6vyzplvwyuqqlcam23

I managed once again to catch this message 4 days after invoice expiration. Sorry about that. Can you post a new one (helpful if it has an arbitrarily long expiration time).

**Comment by nullcount** [comment]
@Reckless-Satoshi this one has a long expiry: 

lnbc999548420p1pjmq2lapp59m5z044l3x3fngamq0mn5cs3t0xwyvcs2dsdv7k87kzzjxakxwcsdqqcqzs2xqyjwflsp5hewqcf5gucsfdcf2uzm2hxgs6pgnlc6fzcectu7cm60mq8wcmlcq9qyyssqu70tscqu34wghzzgsuq0clujk55hjn663dvgrxljadpr449tgmzs43tlnm2wsssl2unye9whhnfeeljtfmnzf62cjdw9l9e68zlfe4sqdpzhqa

**Pull request merged**
