### PR TITLE
French translation Quick Start Guide pages

### PR DESCRIPTION
**Pull request by jinformatique**
## What does this PR do?
Translation in French for Quick Start Guide pages.

Added files in '`docs/_pages/docs/`' with same filename + '`_fr.md`'

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Hey @jinformatique , this is super useful! Thank you very much.

We probably need to solve some conflicts before merging. It seems permalinks might conflict with the ones of the English site.
`permalink: /docs/quick-start/` .

Most likely, in order to introduce languages to the markdown jekyll site, we need a refactorization. Instead of `/_pages/docs/<files>` we could add one more level `/_pages/docs/en/<files>` and `_pages/docs/fr/<files>`, we can remove the `_fr.md` from each of the files. Then we can re-write every single `permalink` property to have the language code in it, for example `/docs/quick-start/en` the `/docs/ . This will allow for all pages to be visible and indexable by browsers.

It is unclear though how we are going to fix the `_data/navigation.yml` to accommodate for multiple languages. Adding every route manually seems like a tedious work.

**Comment by jinformatique** [comment]
Ok, let me know when the rewamp on integrating multiple languages would be done. I could then make the according changes to the files and resubmit French translation. I hope you'll be able to find a way to automatize it, not to add every route manually.

**Comment by Reckless-Satoshi** [comment]
Can you refactor the new files you created into `/_pages/docs/fr/<files>` and add `/fr` to the permalink of everyfile? `permalink: /docs/fr/quick-start/` This way we can already merge and the content will be indexable by search engines.

**Comment by jinformatique** [comment]
No worries, I did the changes.

**Comment by Reckless-Satoshi** [comment]
Awesome! It seems this PR re-introduces a file that had been deleted in `main, the document is`11-api-v0.1.md`. Can you delete it?

We are merging. Please, accept a small donation of 100K Sats for this contribution. Submit an invoice with a long expiration time from a proxy node id.

Thank you!

**Comment by jinformatique** [comment]
Hi, sorry for the trouble with the wrong file added. It's cleaned up now.
Here is a normal invoice for now, I'll look deeper how to provide one from a proxy node id. For now I have no idea.

lnbc1m1pj4hsdlsp5cwcwkmwtjkzc76x7w2gqtp5wa92hkrqx7afteraxmlzrr02q0g4qpp5vefjrs48ttln79stzhwks3h2zk3gws6cn60xg33v8590qdvh450shp5uwcvgs5clswpfxhm7nyfjmaeysn6us0yvjdexn9yjkv3k7zjhp2sxq9z0rgqcqpjrzjqtc63jrkql6ptj8j9sq9jvqzwav5rh4y3p5uugcfdte8kr8aes9kjzufjuqqwxqqqqqqqqqqqqqqqeqqjq9qxpqysgqqe3wppydz4ghk8tqzccjl52066xklmw6n8tr67fu8qncedc6qaqh4dygedja3a3peqevufkh6gs7qzc987ct4vteml4fnd8wjjr5hhgpq2de7l

**Comment by Reckless-Satoshi** [comment]
> lnbc1m1pj4hsdlsp5cwcwkmwtjkzc76x7w2gqtp5wa92hkrqx7afteraxmlzrr02q0g4qpp5vefjrs48ttln79stzhwks3h2zk3gws6cn60xg33v8590qdvh450shp5uwcvgs5clswpfxhm7nyfjmaeysn6us0yvjdexn9yjkv3k7zjhp2sxq9z0rgqcqpjrzjqtc63jrkql6ptj8j9sq9jvqzwav5rh4y3p5uugcfdte8kr8aes9kjzufjuqqwxqqqqqqqqqqqqqqqeqqjq9qxpqysgqqe3wppydz4ghk8tqzccjl52066xklmw6n8tr67fu8qncedc6qaqh4dygedja3a3peqevufkh6gs7qzc987ct4vteml4fnd8wjjr5hhgpq2de7l

b7417f35820c68cbf22180263e48d4381f7b898521f0cacce6cca6524449c053

**Pull request merged**
