### PR TITLE
Fix order flow

### PR DESCRIPTION
**Pull request by KoalaSat**
## What does this PR do?
- Fix token input update when switching robot
- Fix order take
- Fix chat error page

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Review by Reckless-Satoshi — APPROVED** [review]
Hey @KoalaSat , these look good. Merging as is for another round of tests. Please submit an invoice of 150K Sats (it's hard to evaluate what amount is right for every PR, very arbitrary :sweat_smile: )

**Comment by KoalaSat** [comment]
😅 
```
lnbc1500u1pjedm2npp5ta8jaqxmnqvv0rcgkt92v2whhducd3jmg6wcaknnmkcu7s66vkdsdqqcqzzsxqyz5vqsp55yaaeu8dcm5kx0mypw5uanwsfwvhnp5sql4qyrjceffzpyg267xq9qyyssq95kv06tj0mrq25phmu66ctnumnlx4r8knh3f9mrrh8w2drwwpnwz3cty6xjy95x4lfk4wy8r9s522ctzwka942hewkk76xlnkdpupygpl32aqh
```

**Comment by Reckless-Satoshi** [comment]
> lnbc1500u1pjedm2npp5ta8jaqxmnqvv0rcgkt92v2whh

It seems I missed the expiration. Could you submit a new one? Thank you!

**Comment by KoalaSat** [comment]
`lnbc1500u1pjejkttpp50w6dux5fv7ke8la28a0p4qmtqmyp4j22mt5z3luxugvnmdh7qsxqdq5g9kxy7fqd9h8vmmfvdjscqzzsxqyz5vqsp593uywpj6zwvpk7a7ucv4e8vttae3w7zu58jufegdgjp3q3h6sswq9qyyssqatp65hp0arsxmj4m8k6e3e72y7eu3t73wzuxd5etpwnls3ttp7l90aeeaagwkskeucwf3330fxz458cnnthemw4r6hpqv7grm9zc9xgq0kpvyf`

**Comment by Reckless-Satoshi** [comment]
> lnbc1500u1pjejkttpp50w6dux5fv7ke8la28a0p4qmtqmyp4j22mt5z3luxugvnmdh7qsxqdq5g9kxy7fqd9h8vmmfvdjscqzzsxqyz5vqsp593uywpj6zwvpk7a7ucv4e8vttae3w7zu58jufegdgjp3q3h6sswq9qyyssqatp65hp0arsxmj4m8k6e3e72y7eu3t73wzuxd5etpwnls3ttp7l90aeeaagwkskeucwf3330fxz458cnnthemw4r6hpqv7grm9zc9xgq0kpvyf

faee69c56f0321de77a808ff681753620200f1faf98c89851a5b5d560359f8ce

**Pull request merged**
