### PR TITLE
add lightning protobuf files in gitignore

### PR DESCRIPTION
**Pull request by jerryfletcher21**
## What does this PR do?
This way the `.proto` files generated by `scripts/generate_grpc.sh` are ignored and the git environment is kept clean.

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Looks good! Please accept a 10K Sats tip from the DevFund ( +1 week expiration time if possible) 🚀

**Comment by jerryfletcher21** [comment]
lnbc100u1pn8kyrysp59vzftuda72dx80qtvclp7mcga9433rvgdpqy46gsyg9xw5gdd8yqpp5fejsun09q4nr4j4qrnphrt5ax832dj04387t5d7ry4ksgme6xh7sdqqxq9zf6sqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgq0xsauk6vpjg880fgaythnznhwv8j8a7y7negpz3uvsul6l8g2gxqde2lujx86wt7e6saxr0wet6f0x894j72muqddhjfruf5uxyrxqqq23dhjv

**Comment by jerryfletcher21** [comment]
@KoalaSat 

`lnbc100u1p58pu0xsp55hlme99pyr84j95n9nxs6adl5ntsf6w58g557ymkj8slrzjgczpqpp5ww479yu38ek3ezqdlg39jyylye4exp990ucv36s9s3cxv0qkdruqdqqxq9yn4qqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgq8z4auf2084jw3dvpazh509fa7spaf394aysqvdxls0qyr8ky0c352txel3zdxzds6869lve5t3640hpdta4jv2vtaws3hlkvgwnum6spkn95gj`

**Comment by KoalaSat** [comment]
8e14f52ef303c3038c6fe2073df389855451c1077fe82cd3ecbd3e7e48b0b334

**Pull request merged**
