### PR TITLE
portuguese translation

### PR DESCRIPTION
**Pull request by thayronepaula**
## What does this PR do?
Translate some strings to portuguese language

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Hey @thayronepaula , thank you for this helpful contribution to PT speakers!

Please post an invoice with a long expiration time (+24h) from a proxy wallet for a 20K Sats tip.

**Comment by thayronepaula** [comment]
> Hey @thayronepaula , thank you for this helpful contribution to PT speakers!
> 
> Please post an invoice with a long expiration time (+24h) from a proxy wallet for a 20K Sats tip.

lnbc200u1pnqfj8wpp5lmk8l8tsev794hax2x63v6rtpdjn4f5sx6hjwkjz0z307eggeadqdpg235xzmntwvsxvmmjyp6xjurn9ss9ymmzdaekzarncqzzsxqyz5vqsp533qslwpgwj8wrh8f09pwhf3lzrw4lhd3grq2kjsxfuqcznnhkn5s9qyyssq7307h694w8xq0xkahafknkclv34nqnpylys94eevfeasgz2mvv75r9t6vfan8r6jl8t5d2xkfaqzywjmc8zq25spw34fwws6wpncqfsphmgc2e

**Comment by Reckless-Satoshi** [comment]
> lnbc200u1pnqfj8wpp5lmk8l8tsev794hax2x63v6rtpdjn4f5sx6hjwkjz0z307eggeadqdpg235xzmntwvsxvmmjyp6xjurn9ss9ymmzdaekzarncqzzsxqyz5vqsp533qslwpgwj8wrh8f09pwhf3lzrw4lhd3grq2kjsxfuqcznnhkn5s9qyyssq7307h694w8xq0xkahafknkclv34nqnpylys94eevfeasgz2mvv75r9t6vfan8r6jl8t5d2xkfaqzywjmc8zq25spw34fwws6wpncqfsphmgc2e

Got Invoice expired. Did not catch it in time. Can you post a new one? :)

**Comment by thayronepaula** [comment]
> > lnbc200u1pnqfj8wpp5lmk8l8tsev794hax2x63v6rtpdjn4f5sx6hjwkjz0z307eggeadqdpg235xzmntwvsxvmmjyp6xjurn9ss9ymmzdaekzarncqzzsxqyz5vqsp533qslwpgwj8wrh8f09pwhf3lzrw4lhd3grq2kjsxfuqcznnhkn5s9qyyssq7307h694w8xq0xkahafknkclv34nqnpylys94eevfeasgz2mvv75r9t6vfan8r6jl8t5d2xkfaqzywjmc8zq25spw34fwws6wpncqfsphmgc2e
> 
> Got Invoice expired. Did not catch it in time. Can you post a new one? :)

@Reckless-Satoshi of course.

lnbc200u1pnqd047pp5a6hazpn720sua6e9mzkr8v9fduc7cv0gez78s699lv42m54vhx2qdpgw35xzmntwvsxvmmjyp6xjurn9ss8ymmzdaekzarncqzzsxqyz5vqsp506n2pyqxsgq4afqcv86d30rlv0d4jlj4ue2sed2czp2q5chf8zjs9qyyssqg8pvkhznc9jxdw5ssrzr392fkeuq05pq3fyelnave9uz4hfuj0kqfyer20jnkhh47vlerp7c32zdc2x4xvr2k22f38wk8p9zh9p6qagpx93cx6

**Comment by Reckless-Satoshi** [comment]
> lnbc200u1pnqd047pp5a6hazpn720sua6e9mzkr8v9fduc7cv0gez78s699lv42m54vhx2qdpgw35xzmntwvsxvmmjyp6xjurn9ss8ymmzdaekzarncqzzsxqyz5vqsp506n2pyqxsgq4afqcv86d30rlv0d4jlj4ue2sed2czp2q5chf8zjs9qyyssqg8pvkhznc9jxdw5ssrzr392fkeuq05pq3fyelnave9uz4hfuj0kqfyer20jnkhh47vlerp7c32zdc2x4xvr2k22f38wk8p9zh9p6qagpx93cx6

d81ce5d20ab47ace1849101bc4b348f92f197aad6f2999440ba7b0ba66fe60dc

**Pull request merged**
