### PR TITLE
Change getRobot by getSlot

### PR DESCRIPTION
**Pull request by KoalaSat**
## What does this PR do?
There is a big difference between:
- `garage.getRobot().active_order_id`: order id of the last coordinator in return robot information
- `garage.getSlot().ActiveOrderId`: order id of an active order in one of the coordinators

I just removed the possibility to directly access to the robot through the garage and force to always land first into the slot  (`garage.getSlot().robot.found`) so it's clear where the aggregated information is (`garage.getSlot().ActiveOrderId`).

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by KoalaSat** [comment]
Maybe at some point, we should review this and store the same robot information separated by coordinator, with a actual status, a bad coordinator might introduce wrong robot data and break the front-end.

**Comment by Reckless-Satoshi** [comment]
> robot information separated by coordinator,

Yes this is a must. I was envisioning `robot` to be one more attribute to the `Coordinator` model, however, that is difficult to reconcile with the Garage.

**Comment by KoalaSat** [comment]
> that is difficult to reconcile with the Garage.

Maybe storing in the garage slot the specific data from each coordinator? That woudl also simplify the actual Slot entity

```
slot = {
  token: 123,
  activeCoordinator: 'exp'
  lastCoordinator: 'satstralia',
  coordinatorActivity: {
    'exp': { ... robot ... }
    'satstralia': { ... robot ... }
  }
}
```

**Comment by Reckless-Satoshi** [comment]
> activeCoordinator: 'exp'
>   lastCoordinator: 'satstralia',
>   coordinatorActivity: {
>     'exp': { ... robot ... }
>     'satstralia': { ... robot ... }

Ouh yes! This is probably the most elegant solution!

**Comment by Reckless-Satoshi** [comment]
Merging to v0.6.0 as is! Thank you @KoalaSat

**Pull request merged**
