### PR TITLE
Proposes a new Reviews section to main site

### PR DESCRIPTION
**Pull request by athena-alpha**
## What does this PR do?
Proposes a new Reviews section in the README and main site for reviews and / or feature pieces where RoboSats is mentioned. Also updated our guide to v0.5.0

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Hey @athena-alpha , this is a good idea! 

It is however, a little bit strange that we add a Reviews section with only one review. Can we enhance this PR by adding other reviews that we know of? I can think of these two:
- Bitcoin Magazine: https://bitcoinmagazine.com/business/robosats-private-bitcoin-exchange
- KYC not me: https://kycnot.me/exchange/robosats

It is a bit blurry to me how to differentiate tutorials and reviews.

**Comment by athena-alpha** [comment]
The main difference between Reviews and Tutorials is the reviews gives general opinions of the service and goes through all the features, pros, cons etc etc. Tutorials is more of a walk through of individual (or overall) features such as how to buy, sell etc. Usually these are separate, but some sites merge them.

We've added your suggested Reviews and a 3rd one we found too. We probably should have also mentioned that this new Review section was meant to be just the start of a growing list over time, not just us haha

Also feel free to keep / change the styles we've added to the main home.md file to help centre things etc.

**Comment by Reckless-Satoshi** [comment]
Looking great! I will push a follow up commit adding all of the new logos on `home.md` into the static files so they do not get lost. 

Once again, thank you for your contributions to P2P :rocket:

**Comment by athena-alpha** [comment]
Looks awesome and it's our pleasure!

**Pull request merged**
