### PR TITLE
Return json output instead of html when wrong token in Header Authorization

### LINKED ISSUE #1246: Html instead of json output returned when wrong token in Header Authorization
**Describe the bug**

When a wrongly encoded token is present in the Header Authorization, or when the token is correctly encoded but it is not yet present in the coordinator database and the PGP key of the new robot is not present in the Header Authorization, a general html Server Error is returned, instead of a simpler to handle json output specifying the error.

In [robosats/middleware.py](https://github.com/RoboSats/robosats/blob/main/robosats/middleware.py) this AuthenticationFailed Exception for some reason is converted in the general html Server Error below:
```
if not is_valid_token(token_sha256_b91):
    raise AuthenticationFailed(
        "Robot token SHA256 was provided in the header. However it is not a valid 39 or 40 characters Base91 string."
    )
```

**To Reproduce**
```
$ curl --socks5-hostname localhost:9050 --no-progress-meter -H 'Authorization: Token wrong-token' http://robosats6tkf3eva7x2voqso3a5wcorsnw34jveyxfqi2fu7oyheasid.onion/api/robot/

<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
```
```
$ curl --socks5-hostname localhost:9050 --no-progress-meter -H 'Authorization: Token 6hZMgl#kS_lx#Jx4T&;CDECXNLl@Oh8^`ei1Xi?D' http://robosats6tkf3eva7x2voqso3a5wcorsnw34jveyxfqi2fu7oyheasid.onion/api/robot/

<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
```

**Expected behavior**
```
$ curl --socks5-hostname localhost:9050 --no-progress-meter -H 'Authorization: Token wrong-token' http://robosats6tkf3eva7x2voqso3a5wcorsnw34jveyxfqi2fu7oyheasid.onion/api/robot/ | jq -r '.'
{
  "bad_request": "Robot token SHA256 was provided in the header. However it is not a valid 39 or 40 characters Base91 string."
}
```
```
$ curl --socks5-hostname localhost:9050 --no-progress-meter -H 'Authorization: Token 6hZMgl#kS_lx#Jx4T&;CDECXNLl@Oh8^`ei1Xi?D' http://robosats6tkf3eva7x2voqso3a5wcorsnw34jveyxfqi2fu7oyheasid.onion/api/robot/ | jq -r '.'
{
  "bad_request": "On the first request to a RoboSats coordinator, you must provide as well a valid public and encrypted private PGP keys"
}
```

### PR DESCRIPTION
**Pull request by jerryfletcher21**
## What does this PR do?
Fixes #1246

In [robosats/middleware.py](https://github.com/RoboSats/robosats/blob/main/robosats/middleware.py) return a JsonResponse instead of raising AuthenticationFailed Exception that is turned into the general html error by django.

rest_framework.response.Response should not be used in middleware, will return django.template.response.ContentNotRenderedError.

## Checklist before merging
- [X] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Hey @jerryfletcher21 thank you very much for this PR. In fact, we should be using `JsonResponse()` on all API responses (not currently happening).

Please post a 15K Sats invoice with a long expiration time for a small DevFund tip.

**Comment by jerryfletcher21** [comment]
lnbc150u1pn8yxfhsp524awjx3pntzuzm2kax5te7mygc48k55g7k9672e3dml9su7qy9nqpp5q8prrwdt3yfrwtv4kpnu9esv02lexvzqhf5scc5r8203ca0hmu8sdqqxq9zf6sqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgqkzryh86v5l03e6x8un4840g5595p2xp3hp0wv82ywyarlrmj9kphg7g8j5533hxcsgrx2sq5gu37glmjltfggn28w3253eyrae8yumspjqycmj

**Comment by jerryfletcher21** [comment]
@KoalaSat 

`lnbc150u1p58pu2hsp5sdutlfjj9cz9fxgyn3yrarq59nvgdcruczwl5f0s62j45kd9dfespp5zyv5ts0ylnyyr74jft4j4qxmttqtn8texsl65hcnc6lvps34fnnqdqqxq9yn4qqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgq5llfhs7wuclem2anl20glacxya8gtrxkqffj8zw3pxk2ylr22763dqcsu6y9l9f633v6uhrsyupcca9qz9yz54qjjz74pgvxpnwsr2sp2lwxcj`

**Comment by KoalaSat** [comment]
3d46d845b349df8df7e0a1827259b2c07ea45f07de7100bb4ed9e53106898f02

**Pull request merged**
