### PR TITLE
Fix federation summary

### PR DESCRIPTION
**Pull request by KoalaSat**
## What does this PR do?
Related to https://github.com/RoboSats/robosats/issues/1069 Item 3

From the issue:
> Aggregated summary stats behaves weird. The aggregation is broken. Sometimes is stuck at 0 values. It does not re-trigger on mainnet/testnet switch click. Does not trigger a updateCoordinators() when the ExchangeSummary dialog is opened (as it used to be on v0.5.4). Last 24h average premium is sometimes NaN%.

Also removed a deprecated function

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Aggregation now works reliably Loading bar too! 

Can we fix it so the ExchangeDialog re-renders on each update to the exchange.info ? Maybe it needs to re-render `onFederationUpdate`

**Comment by KoalaSat** [comment]
> Aggregation now works reliably. Loading bar too!
> 
> Can we fix it so the ExchangeDialog re-renders on each update to the exchange.info ? Maybe it needs to re-render `onFederationUpdate`

Updated!

**Comment by KoalaSat** [comment]
@Reckless-Satoshi I think I found a better way to deal with the loading, please don't merge this PR yet

**Comment by KoalaSat** [comment]
@Reckless-Satoshi It's good to go now 🚀

**Comment by Reckless-Satoshi** [comment]
Great! Thank you @KoalaSat Please post an invoice for 150K Sats.

**Comment by KoalaSat** [comment]
```
lnbc1500u1pjlfw5app52jxxr8mlm55xx4qyq6g7jzyyl6pkkfue7vusx4977ds5h2haufesdqqcqzzsxqy8ayqsp5lnmykuw5np7jhtdmcwnescs8p09kk4rg5vzgu3rvtn85mn8ace2s9qyyssqcth7sxtxgugapwfehdx8qtsfxq344knqeu0c4ls8fhfvr0pnn2x4rmrktazyclt93svfs08es8tzrlr6ntk4mas8xhu64vvj6zul43gqq5sw4h
```

**Comment by Reckless-Satoshi** [comment]
> lnbc1500u1pjlfw5app52jxxr8mlm55xx4qyq6g7jzyyl6pkkfue7vusx4977ds5h2haufesdqqcqzzsxqy8ayqsp5lnmykuw5np7jhtdmcwnescs8p09kk4rg5vzgu3rvtn85mn8ace2s9qyyssqcth7sxtxgugapwfehdx8qtsfxq344knqeu0c4ls8fhfvr0pnn2x4rmrktazyclt93svfs08es8tzrlr6ntk4mas8xhu64vvj6zul43gqq5sw4h

b46b4eeac24757b2725690e324bca781c2e41a8e1af32f5aaa787d4993e41a08

**Pull request merged**
