### PR TITLE
Fix collect_phrases.py to work on all OS

### LINKED ISSUE #590: Command "python collect_phrases.py" doesn't work as intended in windows OS.
**Describe the bug**
When executing the command `cd frontend/static/locales; python collect_phrases.py`, needed to complete any PR with new phrases to the user interface, the order of the phrases inside the json is not the same in Windows and Linux.

**To Reproduce**
1. Use Windows OS
2. Clone the project
3. Run the command `cd frontend/static/locales; python collect_phrases.py`

**Expected behavior**
The order of the phrases generated by the command `cd frontend/static/locales; python collect_phrases.py` be the same in all OS.

**Screenshots**
N/A - The error is well documentaded in the **Additional context** area.

**Desktop (please complete the following information):**
 - OS: Windows 11 (WSL 2 - Ubuntu)
 - Browser N/A
 - Version  N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS:  N/A
 - Browser N/A
 - Version  N/A

**Additional context**
The script `collect_phrases.py` uses the function `os.walk` to get all the phrases in the frontend, and the order of the dirs and files returned by the function is not guaranteed as the [oficial documentations](https://docs.python.org/3/library/os.html#os.walk) states.

The problem was found in https://github.com/RoboSats/robosats/pull/577#pullrequestreview-1426253266, and discussed in https://github.com/RoboSats/robosats/pull/577#issuecomment-1548350871 and https://github.com/RoboSats/robosats/pull/577#issuecomment-1548671905

### PR DESCRIPTION
**Pull request by JooVLC**
Changed handcrafted.py to use a OrderedDict instead of a dict (guarantee the order independant of the python 3.x version)

Moved the value of "../../src" to the variable "src_path" to improve readability, and reuse the value again later in code

Changed the "Look for all matching i18n keys" part of code to order the dirs and file in a independant OS way - alphabetical order using the "sort" func of list object

Changed the "Look for all matching i18n keys" part of code to collect all phrases in a OrderedDict (guarantee the order independant of the python 3.x version) and sort the matches

Changed the list indexing in filepath var (filepath[10:]) to the use of os.path.relpath(filepath, src_path) func to improve readability

Changed all_phrases to a OrderedDict (guarantee the order independant of the python version) and use update method of OrderedDict to add the files's phrases and handcrafted phrases to the OrderedDict in order

Changed the loop of matches to inside the if statement (if len(matches) > 0) to improve readability - if the "if statement" is false, the loop was never executed

Changed the "Load existing locale dics and replace keys" part of code to use OrderedDict in the new_phrases var to guarantee the order of the keys insert in json.dump in all OS

Changed the "Load existing locale dics and replace keys" part of code to not substitute the keys "#{counter}" to guarantee the order independant of the json file of the translation.

## What does this PR do?
Fixes #590 

This PR refactor the "frontend/static/locales/collect_phrases.py" and "frontend/static/locales/handcrafted.py" to be python 3.x version independent and OS independent (Using OrderedDict and sorts).

The order of the resulting json files is not same of before. Now the files's name and phrases inside the files are order alphabetically. The handcrafted phrases are order by insertion in original python file.

I think the order of the phrases can be the insertion order in the original Typescript/Javascript file, if needed, but the order of the files's name must be alphabetically in json.

Following 3 json files (PT) to represent the json before change in windows and linux and after change:
- [jsons.zip](https://github.com/RoboSats/robosats/files/11524966/jsons.zip)

## Checklist before merging
- [X] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.
- [N/A] If I added new phrases to the user interface, I have ran `cd frontend/static/locales; python collect_phrases.py` to collect them for translation.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Hey @JooVLC 

This is looking great! I ran the new script and the prettier formatter. Then I created a new branch https://github.com/RoboSats/robosats/tree/test-new-collect-phrases

Can you run the test to fetch that branch and run collect_phrases.py and the pre-commit hook? Ideally, after the two have runs, there should not be any changes to commit (meaning the result in our different OS was identical).

In that branch I also updated the pre-commit hook to always run the collect_phrases.py script if the source files in `frontend/src` have been modified. This way the phrases are always created and formatted right away.

I also see a lint error in this PR in Github "SyntaxError: invalid decimal literal (E999)" supposedly in Line1 of collect_phrases.py . But I do not see this in the code and running the linter locally had a different result. Any idea?

**Comment by JooVLC** [comment]
> Hey @JooVLC
> 
> This is looking great! I ran the new script and the prettier formatter. Then I created a new branch https://github.com/RoboSats/robosats/tree/test-new-collect-phrases
> 
> Can you run the test to fetch that branch and run collect_phrases.py and the pre-commit hook? Ideally, after the two have runs, there should not be any changes to commit (meaning the result in our different OS was identical).
> 
> In that branch I also updated the pre-commit hook to always run the collect_phrases.py script if the source files in `frontend/src` have been modified. This way the phrases are always created and formatted right away.
> 
> I also see a lint error in this PR in Github "SyntaxError: invalid decimal literal (E999)" supposedly in Line1 of collect_phrases.py . But I do not see this in the code and running the linter locally had a different result. Any idea?

I tested how you said, but I received an error. Following the record of the test made:
https://github.com/RoboSats/robosats/assets/30505180/bcf1189a-6136-461f-9526-1fc63455d981
image

~~About the lint error, i don't know. I think can be a problem in the use of pre-commit in my PC, because the line being apontedly is from the file _.git/refs/heads/windows-os-collect_phrases.py_, not the _collect_phrases.py_, being **windows-os-collect_phrases.py** the name of my branch.~~

~~When commiting to the branch **windows-os-collect_phrases.py** I received some errors using pre-commit, and to fix I installed **flake8**, **black** and **isort** with the `pip` command, but before the fix I used the command `pre-commit install --install-hooks --overwrite` describe in [pre-commit's docs](https://pre-commit.com/#pre-commit-install).~~

I think the lint error was caused because the branch's name ends in ".py" and inside the .git folder has a file with a numerical reference of the branch in the first line (the file contain just a line), but the name of this file is the same name of the branch, then the lint read this like a python file (incorrectly). 🤦🤦🤦

**Comment by JooVLC** [comment]
> > Hey @JooVLC
> > This is looking great! I ran the new script and the prettier formatter. Then I created a new branch https://github.com/RoboSats/robosats/tree/test-new-collect-phrases
> > Can you run the test to fetch that branch and run collect_phrases.py and the pre-commit hook? Ideally, after the two have runs, there should not be any changes to commit (meaning the result in our different OS was identical).
> > In that branch I also updated the pre-commit hook to always run the collect_phrases.py script if the source files in `frontend/src` have been modified. This way the phrases are always created and formatted right away.
> > I also see a lint error in this PR in Github "SyntaxError: invalid decimal literal (E999)" supposedly in Line1 of collect_phrases.py . But I do not see this in the code and running the linter locally had a different result. Any idea?
> 
> I tested how you said, but I received an error. Following the record of the test made: https://github.com/RoboSats/robosats/assets/30505180/bcf1189a-6136-461f-9526-1fc63455d981 image
> 
> ~About the lint error, i don't know. I think can be a problem in the use of pre-commit in my PC, because the line being apontedly is from the file _.git/refs/heads/windows-os-collect_phrases.py_, not the _collect_phrases.py_, being **windows-os-collect_phrases.py** the name of my branch.~
> 
> ~When commiting to the branch **windows-os-collect_phrases.py** I received some errors using pre-commit, and to fix I installed **flake8**, **black** and **isort** with the `pip` command, but before the fix I used the command `pre-commit install --install-hooks --overwrite` describe in [pre-commit's docs](https://pre-commit.com/#pre-commit-install).~
> 
> I think the lint error was caused because the branch's name ends in ".py" and inside the .git folder has a file with a numerical reference of the branch in the first line (the file contain just a line), but the name of this file is the same name of the branch, then the lint read this like a python file (incorrectly). 🤦🤦🤦

Sorry, I just installed prettier using `npm install -g prettier` in the cloned branch and it worked. Following the new record of the test made:
https://github.com/RoboSats/robosats/assets/30505180/0a671822-8efb-46ab-8847-7712a9fa8fb2


It worked like a charm, no changes in the file. =)

**Comment by JooVLC** [comment]
@Reckless-Satoshi, I renamed the branch "_windows-os-collect_phrases.py_" to "_windows-os-collect_phrases.py-file_". If you want I can make a new PR using this new branch, I think doing this all the checks will pass.

**Comment by Reckless-Satoshi** [comment]
> It worked like a charm, no changes in the file. =)

Amazing! Indeed, the lint error was very weird. Good catch! Looks ready to be merged. I will merge and then collect statics with the new script in the following commit.

Please, accept a tip of 40K Sats from the devfund. Submit an invoice with a long expiration time from a proxy node id :)

**Comment by JooVLC** [comment]
@Reckless-Satoshi, Following up with the invoice:

lnbc400u1pjx7ccppp5zpaxmf6my55pdxqulq8n68yxv8cmwkwret8r5xh6guma4mpsghqqdqqxqyjw5q9q7sqqqqqqqqqqqqqqqqqqqqqqqqq9qsqsp5g0qeqg6an0ly0lxkyzlyq3fu08c9xdlk2azhx5fpd9uvawcrecvsrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glcll6tqt7js3kq65qqqqlgqqqqqeqqjqyrkfqgjgr40x0k52z7yc35q0ezccg45d7de7wts79sdhvlmhdgjnsqn75lpuvrcswe6jnhg3tx6xfsg2aqahafjhzv2yj2g8ch0lnqqp7hzf6u

**Pull request merged**
