### PR TITLE
add robot status "Seen Recently" where missing in the documentation

### PR DESCRIPTION
**Pull request by jerryfletcher21**
## What does this PR do?
This PR add robot status "Seen Recently" where missing in the documentation.

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Thank you for this fix. 

Please accept a small tip from the devfund for 10K Sats. Submit an invoice with a long expiration time (+1 week).

**Comment by jerryfletcher21** [comment]
lnbc100u1pn8yxv9sp5cplag5l33p7v9zfz9n3vyllm9nk45vrcsx30texqlwlqqxppxvsqpp525gckzsdphh3ykyk39sns87wvcgrhex9zq6rxgz2n5svc5dqlmfqdqqxq9zf6sqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgqtlehcz5ktyyzexhad03gy8cvva9r7p8gfhdexs77xft76asnvwt3nh0au0k5eh8rdn2dpfdkwtuyeajhtxu352jddznstpyprm8w67sq7fkjx5

**Comment by jerryfletcher21** [comment]
@KoalaSat 

`lnbc100u1p58puvgsp5lhcs23ynn6hww6hqzpahv4l5x77nxs6qs8xgsmm36q0fu8stl7uspp58ruy27xrg4f0rhqh04cplk0zga4zcgd8wua4sj5fqe2yca0rynvqdqqxq9yn4qqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgqk7vs6e7j0r85u3jal09vr3nd5jwtw0avl6fp43wdss305yzhvj89qrk5knsv2dejqht69xkw772trsn6h6lltr86asdxxn7zwcjscpspwq7cq0`

**Comment by KoalaSat** [comment]
fd0a1aeb8c998d9f768259c35f2c2c699a5bd84843b77ab30f627337d882c718

**Pull request merged**
