### PR TITLE
New Tor engine and Federation App

### PR DESCRIPTION
**Pull request by KoalaSat**
## What does this PR do?

This PR introduces a new Tor engine for the android App, way more reliable, stable and able to work with WS. 

It also modifies the federation fronted code to work properly with the asynchronous start of the engine.

**To be Fixed**: WebWorkers and Federation avatars

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Hey @KoalaSat, looks ready to merge!

Please share an invoice for **1.2M Sats** for a DevFund developer reward.

**Comment by KoalaSat** [comment]
````
lnbc12m1pnr9z4rpp52mc0rtg0nupyr66m8p4eg65n5k45esw6lyf7ywf5qj0mwmnzphssdqqcqzzsxqyvx5qsp50my45ynuy8rl9qslqlt7m2d35a8y0s2f29jn8409zt884fjvw7tq9qyyssq39tg02htzqqu7076ysefj0jm0mnxc3ucvnmwekpl828cuvte9acpd7txj264u5nfxwuefrw40muhx6t7jhclefw8vc0jtweqx8ah9cgqnhnw5e
````

**Comment by Reckless-Satoshi** [comment]
> lnbc12m1pnr9z4rpp52mc0rtg0nupyr66m8p4eg65n5k45esw6lyf7ywf5qj0mwmnzphssdqqcqzzsxqyvx5qsp50my45ynuy8rl9qslqlt7m2d35a8y0s2f29jn8409zt884fjvw7tq9qyyssq39tg02htzqqu7076ysefj0jm0mnxc3ucvnmwekpl828cuvte9acpd7txj264u5nfxwuefrw40muhx6t7jhclefw8vc0jtweqx8ah9cgqnhnw5e

0648d4a1f66ce6304d64cacbfe5686606b5021e92c9385b79bfcefdaaeebc0d9

**Comment by Reckless-Satoshi** [comment]
Closing on favor of #1262

**Pull request closed without merging**
