### PR TITLE
Update 07-wallets.md

### PR DESCRIPTION
**Pull request by htteot**
doc

## What does this PR do?
Fixes doc

## Checklist before merging
- [ ] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Review by Reckless-Satoshi — APPROVED** [review]
Thank you @htteot for updating the wallets table. 

Please post an invoice for 10K Sats with a long expiration time. We are still pending the reward for #1306 . Feel free to post an invoice for 30K instead to simplify the process :D

**Comment by htteot** [comment]
> Thank you @htteot for updating the wallets table.
> 
> Please post an invoice for 10K Sats with a long expiration time. We are still pending the reward for #1306 . Feel free to post an invoice for 30K instead to simplify the process :D

lnbc300u1pnx7m6hpp5gknn4ramd5fkfgzn0l9rc3a6eurrejfjw7ecp3xg7jg3dcakg88ssp5jgvdqpnuh3zdcd2cjhh6mnucuufzwtzaylwm0rnzlukgfq6arpkqdqsdp68get0wss8g6tscqzynxqyjw5q9qlzqqqqqqqqqqqqqqqqqqqqqqqqqq9scqfppq9t96www0yqtfx3juvvw94g6mc09y6hfdrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glc7qkvqrgk9fsqycqqqqlgqqqqqeqqjqpfa94c3rmdfz6pswtjykcqgkjgjea078v0jfnxqsvfc0rh2qkczh8nnqjtkugud7cwu2fsjmp0tmr82ulsvclmtdn3xtxqfjzxkc2ggp0tvwkm

(set to 1 week expiry) ... Please try this one. If there is still 'no route' I believe opening a channel which is linked to one of the ACINQ nodes(Electrum/Phoenix wallet) may fix it. Or the problem was on my side of the channel...

**Comment by Reckless-Satoshi** [comment]
> lnbc300u1pnx7m6hpp5gknn4ramd5fkfgzn0l9rc3a6eurrejfjw7ecp3xg7jg3dcakg88ssp5jgvdqpnuh3zdcd2cjhh6mnucuufzwtzaylwm0rnzlukgfq6arpkqdqsdp68get0wss8g6tscqzynxqyjw5q9qlzqqqqqqqqqqqqqqqqqqqqqqqqqq9scqfppq9t96www0yqtfx3juvvw94g6mc09y6hfdrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glc7qkvqrgk9fsqycqqqqlgqqqqqeqqjqpfa94c3rmdfz6pswtjykcqgkjgjea078v0jfnxqsvfc0rh2qkczh8nnqjtkugud7cwu2fsjmp0tmr82ulsvclmtdn3xtxqfjzxkc2ggp0tvwkm

20caa5d52c9ab65cd5efefed08469cdedb84e77fd0f4453c7c29d668735e08c9

**Comment by htteot** [comment]
thank you

**Pull request merged**
