### PR TITLE
remove leftover of avatar generator

### PR DESCRIPTION
**Pull request by jerryfletcher21**
## What does this PR do?
Remove leftover from https://github.com/RoboSats/robosats/commit/0026fc0d68b0479c9c8cfc992dce11ac52d77283

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Indeed, these are also no longer needed. Good catch!

Merging :rocket: Please post an invoice for 15K (with an absurd expiration time :D)

**Comment by jerryfletcher21** [comment]
> Please post an invoice for 15K (with an absurd expiration time :D)

lnbc150u1png4nrhsp5le474nupjt7l6d66322f8gpqh8gk80sx3ce3yf7c7qv4uu07tr6qpp56n0wthr9a4vpskqn6ywmrrzjg20h0sg0uc8hht2wqstkjfkclz5qdqqxq9zf6sqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgqrfnet8e5mm90pxyrlz29scq3ce0ggrmahus4hvcz9yp3jcr8jnhzu5sstqwff9draf8z7kad0za84f08pu9uurpnt3972frmvll5lzsqfpd7r8

**Comment by jerryfletcher21** [comment]
@KoalaSat 

`lnbc150u1p58pusssp5klx9f6zcst288hqzzsqqfj3mt5rjd6ctplhvwm5ku3fdlapq5skspp569538yq8dl9z8dwh8kskf0p6ftvff4lgud37xc7r0fy5c5qq6jxqdqqxq9yn4qqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgq6zuu4myw9h7ehzc72jpm0k8genrwuf92en8tpfwxm8h8pvmwgnl8vxy8ch3hx4capgxtp3pld792n74gja7cu4dt7juddj6rq04lrzcqfh5449`

**Comment by KoalaSat** [comment]
6179ad8cdf2391f3a10a3d9bb433b326044665be0d0f149b3d26740feda853de

**Pull request merged**
