### PR TITLE
improve/update documentation in api/oas_schemas.py

### PR DESCRIPTION
**Pull request by jerryfletcher21**
## What does this PR do?
Some improvements in the documentation that I noticed while writing [roboauto](https://github.com/jerryfletcher21/roboauto) in https://learn.robosats.com/docs/api.

Specify that the amount of the invoice sent in `update_invoice` should take into consideration `routing_budget_ppm`.

Specify that the signed messages should be signed with SHA512. 

Fix a repetition and a broken link.

Specify that the PGP key should be ed25519/cert,sign+cv25519/encr.

Remove the warning that in the future canceling not taken orders might result in losing the bond.
In roboauto I have an action `recreate-order` that updates an online order by canceling and recreating with
some parameters changed. Obviously if the bond is lost when canceling an order I will have to remove this feature.
I spoke with @Reckless-Satoshi and he confirmed that the bond will not be lost in the future.

## Checklist before merging
- [X] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Thank you for catching these issues and improving our API docs for all future developers. 

Please post an invoice for 15K Sats with a long expiration time for a small DevFund tip.

**Comment by jerryfletcher21** [comment]
lnbc150u1pn8yx9asp5uex5zkfr2596tfsak23se894hdcx5amg2exs8cp29jnmmmcs4m3spp5nz8hzkv44pp5v69kp02pegn90p2am560u089lhu6qq4g35nju0jqdqqxq9zf6sqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgqwa437davyllgu8hxl9cz4ftmvjf5p0k2mmp82wy43cxy7k4320ahrtfkyvl58zxxhvg0xdn2258n8png9hqde3qytwv0l623su2l2rcqdaawn7

**Comment by jerryfletcher21** [comment]
@KoalaSat

`lnbc150u1p58pu8esp58g3nmnsa4c4ulf9scqsj8s3c8rtzwh0zr6hccgu85ug35kxpkngspp5e84zt5wt5c2qqqdyj3lcpe5qht5c89qtna22k9rc2stctr8md2esdqqxq9yn4qqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgqsunf0aehfxrt84svngm0qj8dj85up883rngcskt56hlqnzfgcfah7gfxqudq4cm3zy068zn6kmyft5uqvt6pplcdnftzccld2ue937cqmerraa`

**Comment by KoalaSat** [comment]
e21d8c914368d46a8dc34fa962a134beabc512b6d54d5799005ed42a1a60c239

**Pull request merged**
