### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by jimtoshi**
Changed dev script to fix "Javascript heap out of memory" error when running docker-compose.

## What does this PR do?
Fixes #<ISSUE_NUMBER>

This PR introduces/refactors/...

## Checklist before merging
- [ ] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Review by Reckless-Satoshi — APPROVED** [review]
Looks good!

**Comment by Reckless-Satoshi** [comment]
Hey @jimtoshi , amazing! Thank you for this fix, as it seemed to be a recurrent issue some new robodevs where having with the webpack dev script. Merging as is!

Please accept a tip for 5K Sats. Drop an invoice from a proxy wallet with +24h expiration time.

**Comment by jimtoshi** [comment]
Awesome!

Here's an invoice from WOS...  not sure what the default expiration is but if its too short, I'm also dropping my npub on nostr if you'd rather send a zap.  Thanks again!

lnbc50u1pjdurhrpp5pcytczlxjnpa7el54xv8ml43xap28alhuvdkz9c248fpcemy8jqqdqu2askcmr9wssx7e3q2dshgmmndp5scqzzsxqyz5vqsp5tx868uqhx04s287hpc4wcxl56p53uqatl3mzevsgr204mewetszq9qyyssq9yf2245dyczkdlu3fx4akaapu2ychqhsq8w2duf9hm5glp7wsypsjyjlpdn0z00ewhwukhy7n8vcgqdqkeu8pyhe4emswf098cgeluspww7x7k

npub1y06ta47zjez9l8th7h6ca5qd9yly0sqhd38cvtljan487stn7guqeqknvg

**Comment by Reckless-Satoshi** [comment]
> lnbc50u1pjdl8fnpp5awa2dy834p3vf7s0eeyxkyfp9ztwl0jw6dfmfhyrnaxtsj6ysg4qdqu2askcmr9wssx7e3q2dshgmmndp5scqzzsxqyz5vqsp520w97cdqzxpr95q0ekgaq378edu9agqrzc40fdt27ugrjndgkukq9qyyssqx24keda3dq7c3scgsnq878rtsejzz0pmh7mv4ykcumvaaj8gxlmrxxtec448ewag782azulfmckmfm0zmst440cmg37z5qk65nhkwxsq3y338l

89d0dc673b712d51fbf9def2d041c21cf1f89c5c0dce3db84bdaf3d9dac37252

**Pull request merged**
