### PR TITLE
fix warnings DecimalField should be Decimal type

### PR DESCRIPTION
**Pull request by jerryfletcher21**
## What does this PR do?
The warnings were caused by the validators `MinValueValidator` and `MaxValueValidator` inside a `DecimalField`.

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Thank you @jerryfletcher21 these warning were annoying. I believe they came in with the Django v5 update, I eliminated some of them but missed these ones. Please submit an invoice for 20K and a loong expiration time (+1 week) for a small Dev Fund tip :rocket:

**Comment by jerryfletcher21** [comment]
lnbc200u1pn8yxdcsp56mz8378rlywdj5dz0xlgnmsccz3rhpkgp4wt4nn67ty00sttc5rspp5xr9yw6hygphmf490dghnvkdrarnnn0kxaslyldlsy3ezug035xwqdqqxq9zf6sqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgqzzrwkp5v06k9ae4j57uqya6l7lsz6g049xd4kqz57kvt7wx5qhk48h28vfe7fex9dgmrez9egpamwspjxahnl2rustygclhvraw877cqlsfkl0

**Comment by jerryfletcher21** [comment]
@KoalaSat 

`lnbc200u1p58pud5sp5zw2vgg2dkatrp8pe27vahqzxmdtvztrvm9a2x9pva9qwr5rgr9kqpp5yk2h96guxpc87rnd7rvuwargwa6d2239ra7gzvavpee7pcsgdzvqdqqxq9yn4qqcqzysrzjqdllz2m2fe9ukju5fdkjptcgehlkrv6xrswl7rgq4zrfws2d3yduwr8j0yqpv2sqqqqqqqlgqqqqp9sq2q9qxpqysgqxsz93kfk36sapestgz873tgzgg7c0hmd670peqf8r7z4ndv2820srquh6dhnqrujxr37mm5wqjv54uwphqrht2exczeegpkx9p2g85cqqdxagj`

**Comment by KoalaSat** [comment]
6c5cb6062a445fb096d207bacaf12f7b1a79652b4f636b062d8ab66a6cc62424

**Pull request merged**
