### PR TITLE
Update 07-wallets.md

### PR DESCRIPTION
**Pull request by htteot**
## What does this PR do?
Fixes doc

## Checklist before merging
- [ ] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Thank you very much for updating the docs with this precise and clear information.

Please post an invoice for 20K Sats for a small tip from the devfund (if possible +1 week expiration time).

**Comment by htteot** [comment]
> Thank you very much for updating the docs with this precise and clear information.
> 
> Please post an invoice for 20K Sats for a small tip from the devfund (if possible +1 week expiration time).

Thank you

lnbc200u1pn9eawtpp5llhv8w97vk59gg5glx6m235lz0e5j5gl8dqkqce7ak9y4gazr7pqsp5wjagf62n4v5d8yckys9c33scmuwe56uu2v2lhqmmxjxarz7l8ffsdqjw35hqgpqdp68get0wscqzynxqyjw5q9qlzqqqqqqqqqqqqqqqqqqqqqqqqqq9scqfppq4xukcafxw7zc39pze3nzcynw83nt55tdrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glc7qleup88j3s60sqqqqlgqqqqqeqqjqvhs763gh3d0jrh43r2mlsxeqc0wsmujkmvxn3mqdd499yuy2ptshurrjwhyfp4pve8yua6fa4pfxnul4x6uc5tgcenvlf63v3pmkassq2fzggu

**Comment by htteot** [comment]
> Thank you very much for updating the docs with this precise and clear information.
> 
> Please post an invoice for 20K Sats for a small tip from the devfund (if possible +1 week expiration time).

lnbc200u1pnxvv4spp58k29w5lksp23zcxdxtuc4gzksvydrsvr35ngtua3f5mhulugamgqsp508glnh9hxx43mxgnglgy460p82jaf4qxucz8qh7ltgxkxm5r7hwsdqjdp68get0wsszqarfwqcqzynxqyjw5q9qlzqqqqqqqqqqqqqqqqqqqqqqqqqq9scqfppq9t96www0yqtfx3juvvw94g6mc09y6hfdrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glc7qleup88j3s60sqqqqlgqqqqqeqqjqwwwvj6hrrh4tmj293642n5cqzexnzd63xgslyt7gt7tqz920679hrkuqzt699435awgcqw5qkk6rzqt6q4u7e8upa9ay0vmae24dedsqnlpeka

**Comment by Reckless-Satoshi** [comment]
> lnbc200u1pnxvv4spp58k29w5lksp23zcxdxtuc4gzksvydrsvr35ngtua3f5mhulugamgqsp508glnh9hxx43mxgnglgy460p82jaf4qxucz8qh7ltgxkxm5r7hwsdqjdp68get0wsszqarfwqcqzynxqyjw5q9qlzqqqqqqqqqqqqqqqqqqqqqqqqqq9scqfppq9t96www0yqtfx3juvvw94g6mc09y6hfdrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glc7qleup88j3s60sqqqqlgqqqqqeqqjqwwwvj6hrrh4tmj293642n5cqzexnzd63xgslyt7gt7tqz920679hrkuqzt699435awgcqw5qkk6rzqt6q4u7e8upa9ay0vmae24dedsqnlpeka

Sorry for getting so late to this. Getting `No route found` for this invoice (not yet expired).

**Comment by htteot** [comment]
I will reply in the other thread

**Pull request merged**
