### PR TITLE
Book coordinator filter

### PR DESCRIPTION
**Pull request by KoalaSat**
## What does this PR do?
Add coordinator filter to the Book page

image

## Checklist before merging
- [x] Install [pre-commit](https://pre-commit.com/#installation) and initialize it: `pip install pre-commit`, then `pre-commit install`. Pre-commit installs git hooks that automatically check the codebase. If pre-commit fails when you commit your changes, please fix the problems it points out.

### CODE REVIEW

**Comment by Reckless-Satoshi** [comment]
Thank you @Koala for fixing the book loading and adding this Coordinator filter. Please submit a 100K invoice for these contributions :rocket:

**Comment by KoalaSat** [comment]
```
lnbc1m1pjmz74ppp58zgrcq6zdgt0t5kpdxvlq8kzqkyz4ha5a72wwyk7d7gfp8t82dssdqqcqzzsxqyz5vqsp5zv7w0vn7yy6jp9clm6md6el9kz6msu8u02w0whl8nd603luv5zgs9qyyssqtw664cjajzewv2s29hgcwsfnd5fp0xujd7q4m0xqfqs0jgpfkuzz3kpqkwxzx02ate5vw9vznjnmmwyf7p4rktutdjsvc0hghvulamqp0q5jgp
```

**Comment by Reckless-Satoshi** [comment]
> ```
> lnbc1m1pjmz74ppp58zgrcq6zdgt0t5kpdxvlq8kzqkyz4ha5a72wwyk7d7gfp8t82dssdqqcqzzsxqyz5vqsp5zv7w0vn7yy6jp9clm6md6el9kz6msu8u02w0whl8nd603luv5zgs9qyyssqtw664cjajzewv2s29hgcwsfnd5fp0xujd7q4m0xqfqs0jgpfkuzz3kpqkwxzx02ate5vw9vznjnmmwyf7p4rktutdjsvc0hghvulamqp0q5jgp
> ```

Caught this one late, invoice expired yesterday. Can you post a new one? Thank you!

**Comment by KoalaSat** [comment]
lnbc1m1pjm8uxcpp5e4lvsp70sn0dyev3mlkn8t0m8mqq52j84xrvdf24gmrt8qls8g2qdqqcqzzsxqyz5vqsp5la27rve4c006vkm2c5qtpfapszrnj64nyn0jqzq07uxg3aavrc3s9qyyssqkv0hxrzzpzu4hpyedvggurxhap7m68rqhkqlcevzsky73mxlcdyypt9jp9y0v426hapy8gsgn4608csrnyymfxuk9k5n5985ypqzqgcqelpgak

**Comment by Reckless-Satoshi** [comment]
> lnbc1m1pjm8uxcpp5e4lvsp70sn0dyev3mlkn8t0m8mqq52j84xrvdf24gmrt8qls8g2qdqqcqzzsxqyz5vqsp5la27rve4c006vkm2c5qtpfapszrnj64nyn0jqzq07uxg3aavrc3s9qyyssqkv0hxrzzpzu4hpyedvggurxhap7m68rqhkqlcevzsky73mxlcdyypt9jp9y0v426hapy8gsgn4608csrnyymfxuk9k5n5985ypqzqgcqelpgak

c318fb12678f6998e55f6a5141d30d73a01f2c37c8c6c6dd923cdad2e8fba9af

**Pull request merged**
